### ISSUE TITLE
Can not delete volume from Action>delete when in volume details page

### ISSUE THREAD

**Issue by qinguanchao** [zstackorg/zstack-dashboard#4]
Can not delete volume from Actions>delete when in volume details page,but can delete in page Volumes>Action>delete

**Comment by youyk** [comment]
thanks for reporting this issue. Will check

**Comment by youyk** [comment]
Fixed by: https://github.com/zstackorg/zstack-dashboard/commit/d8505f7dae1396f4f7f340ed65f2a5dd95b8f568
