### ISSUE TITLE
端口转发的界面点击后，直接返回仪表盘界面，无法进入细节列表进行操作

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstack-dashboard#51]
![image](https://cloud.githubusercontent.com/assets/10667305/12678243/c8504a3e-c6d8-11e5-8ec4-7cf6e682df82.png)
端口转发的界面点击后，直接返回仪表盘界面，无法进入细节列表进行操作，
例如无法detach 并attache切换至其他虚拟机。

**Comment by QiRaining** [comment]
@lstfyt fix
