### ISSUE TITLE
Cannot specify rabittmq ip for dashboard starting

### ISSUE THREAD

**Issue by ghxandsky** [zstackorg/zstack-dashboard#74]
Cannot specify rabittmq ip for dashboard starting using:

`/etc/init.d/zstack-dashboard start --rabbitmq "zstack:zstack123@172.20.12.191:55672"`

It always reads from zstack.propertie.

**Comment by youyk** [comment]
Yes. It is by designed. The rabbitmq info is read from zstack.properties.
