### ISSUE TITLE
Change VM instance offering doesn't work when there are several instance offerings. 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack-dashboard#75]
If the system has a few of instance offering (like > 6), the change instance offering action can only change the first 2 option,

The zstack-cli can successfully change the instance offering. So this should be a UI bug in java script.

**Comment by youyk** [comment]
@tolbkni are you able to look at this issue?

**Comment by tolbkni** [comment]
Confirmed. I will submit a patch later.
