### ISSUE TITLE
after delete the instance offering , UI could not change the instance offering with stopped guest

### ISSUE THREAD

**Issue by lstfyt** [zstackorg/zstack-dashboard#84]
after delete the instance offering , UI could not change the instance offering with stopped guest

**Comment by tolbkni** [comment]
@youyk 在 instance 使用该 instance offering 的情况下允许删除 instance offering？

**Comment by youyk** [comment]
@tolbkni It is allowed to delete instance offering when VM is using it.

**Comment by youyk** [comment]
instance offering configuration is just a reference to VM, but not a mandatory binding. So after deleting the instance offering, the VM configuration still record the cpu, memory information. And we can change it to another instance offering.
