### ISSUE TITLE
Add new storage shared mount point support 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack-dashboard#85]
ZStack 1.2 support new storage type:
shared mount point

The API is:
APIAddSharedMountPointPrimaryStorageMsg

The implemation could refer the local storage: APIAddLocalPrimaryStorageMsg

**Comment by youyk** [comment]
APIAddSharedMountPointPrimaryStorageMsg parameters include:

description=   name=     url=    zoneUuid=   

url is a local path, just like Local Storage. e.g. /zstack_ps

The testing method:

The shared mount point is similar with local storage.  The difference is all Hosts in cluster with shared mount point primary storage will see same contents in same shared mount point url. 

The background implementation of shared mount point is distributed file system, like OCFS2 GFS2. But we can use NFS to test it as well. For exmaple, we can create a NFS server and manually mount it in every hosts same folder, like /zstack_ps, Then use this folder as shared mount point url. After add it, all hosts will share the same url.

**Comment by tolbkni** [comment]
pull request #93 implement this
